 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.6.4
     steps:
       - checkout
       - run: 
           name: isntall dependencies
           command: |
                   sudo pip install -r requirements.txt
       - run:
           name: run linting test
           command: |
                   flake8 --statistics
